import { config } from 'dotenv'
import { resolve } from 'path'
config({ path: resolve(__dirname, '../.env') })

import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const stickers = [
  { code: '00', title: 'Panini Logo', section: 'We Are Panini', type: 'foil' },
  { code: 'FWC1', title: 'Official Emblem', section: 'FIFA World Cup 2026', type: 'foil' },
  { code: 'FWC2', title: 'Official Emblem', section: 'FIFA World Cup 2026', type: 'foil' },
  { code: 'FWC3', title: 'Official Mascots', section: 'FIFA World Cup 2026', type: 'foil' },
  { code: 'FWC4', title: 'Official Slogan', section: 'FIFA World Cup 2026', type: 'foil' },
  { code: 'FWC5', title: 'Official Ball', section: 'FIFA World Cup 2026', type: 'foil' },
  { code: 'FWC6', title: 'Canada', section: 'Host Countries and Cities', type: 'foil' },
  { code: 'FWC7', title: 'Mexico', section: 'Host Countries and Cities', type: 'foil' },
  { code: 'FWC8', title: 'USA', section: 'Host Countries and Cities', type: 'foil' },
  { code: 'FWC9', title: 'Italy 1934', section: 'FIFA World Cup History', type: 'foil' },
  { code: 'FWC10', title: 'Uruguay 1950', section: 'FIFA World Cup History', type: 'foil' },
  { code: 'FWC11', title: 'West Germany 1954', section: 'FIFA World Cup History', type: 'foil' },
  { code: 'FWC12', title: 'Brazil 1962', section: 'FIFA World Cup History', type: 'foil' },
  { code: 'FWC13', title: 'West Germany 1974', section: 'FIFA World Cup History', type: 'foil' },
  { code: 'FWC14', title: 'Argentina 1986', section: 'FIFA World Cup History', type: 'foil' },
  { code: 'FWC15', title: 'Brazil 1994', section: 'FIFA World Cup History', type: 'foil' },
  { code: 'FWC16', title: 'Brazil 2002', section: 'FIFA World Cup History', type: 'foil' },
  { code: 'FWC17', title: 'Italy 2006', section: 'FIFA World Cup History', type: 'foil' },
  { code: 'FWC18', title: 'Germany 2014', section: 'FIFA World Cup History', type: 'foil' },
  { code: 'FWC19', title: 'Argentina 2022', section: 'FIFA World Cup History', type: 'foil' },
  { code: 'MEX3', title: 'Johan Vasquez', section: 'Mexico', type: '-' },
  { code: 'MEX4', title: 'Jorge Sánchez', section: 'Mexico', type: '-' },
  { code: 'MEX5', title: 'Cesar Montes', section: 'Mexico', type: '-' },
  { code: 'MEX6', title: 'Jesus Gallardo', section: 'Mexico', type: '-' },
  { code: 'MEX7', title: 'Israel Reyes', section: 'Mexico', type: '-' },
  { code: 'MEX8', title: 'Diego Lainez', section: 'Mexico', type: '-' },
  { code: 'MEX9', title: 'Carlos Rodriguez', section: 'Mexico', type: '-' },
  { code: 'MEX10', title: 'Edson Alvarez', section: 'Mexico', type: '-' },
  { code: 'MEX11', title: 'Orbelin Pineda', section: 'Mexico', type: '-' },
  { code: 'MEX12', title: 'Marcel Ruiz', section: 'Mexico', type: '-' },
  { code: 'MEX13', title: 'Team Photo', section: 'Mexico', type: '-' },
  { code: 'MEX14', title: 'Érick Sánchez', section: 'Mexico', type: '-' },
  { code: 'MEX15', title: 'Hirving Lozano', section: 'Mexico', type: '-' },
  { code: 'MEX16', title: 'Santiago Giménez', section: 'Mexico', type: '-' },
  { code: 'MEX17', title: 'Raúl Jiménez', section: 'Mexico', type: '-' },
  { code: 'MEX18', title: 'Alexis Vega', section: 'Mexico', type: '-' },
  { code: 'MEX19', title: 'Roberto Alvarado', section: 'Mexico', type: '-' },
  { code: 'MEX20', title: 'Cesar Huerta', section: 'Mexico', type: '-' },
  { code: 'RSA1', title: 'Emblem', section: 'South Africa', type: 'foil' },
  { code: 'RSA2', title: 'Ronwen Williams', section: 'South Africa', type: '-' },
  { code: 'RSA3', title: 'Sipho Chaine', section: 'South Africa', type: '-' },
  { code: 'RSA4', title: 'Aubrey Modiba', section: 'South Africa', type: '-' },
  { code: 'RSA5', title: 'Samukele Kabini', section: 'South Africa', type: '-' },
  { code: 'RSA6', title: 'Mbekezeli Mbokazi', section: 'South Africa', type: '-' },
  { code: 'RSA7', title: 'Khulumani Ndamane', section: 'South Africa', type: '-' },
  { code: 'RSA8', title: 'Siyabonga Ngezana', section: 'South Africa', type: '-' },
  { code: 'RSA9', title: 'Khuliso Mudau', section: 'South Africa', type: '-' },
  { code: 'RSA10', title: 'Nkosinathi Sibisi', section: 'South Africa', type: '-' },
  { code: 'RSA11', title: 'Teboho Mokoena', section: 'South Africa', type: '-' },
  { code: 'RSA12', title: 'Thalente Mbatha', section: 'South Africa', type: '-' },
  { code: 'RSA13', title: 'Team Photo', section: 'South Africa', type: '-' },
  { code: 'RSA14', title: 'Bathusi Aubaas', section: 'South Africa', type: '-' },
  { code: 'RSA15', title: 'Yaya Sithole', section: 'South Africa', type: '-' },
  { code: 'RSA16', title: 'Sipho Mbule', section: 'South Africa', type: '-' },
  { code: 'RSA17', title: 'Lyle Foster', section: 'South Africa', type: '-' },
  { code: 'RSA18', title: 'Iqraam Rayners', section: 'South Africa', type: '-' },
  { code: 'RSA19', title: 'Mohau Nkota', section: 'South Africa', type: '-' },
  { code: 'RSA20', title: 'Oswin Appollis', section: 'South Africa', type: '-' },
  { code: 'KOR1', title: 'Emblem', section: 'South Korea', type: 'foil' },
  { code: 'KOR2', title: 'Hyeon-woo Jo', section: 'South Korea', type: '-' },
  { code: 'KOR3', title: 'Seung-Gyu Kim', section: 'South Korea', type: '-' },
  { code: 'KOR4', title: 'Min-jae Kim', section: 'South Korea', type: '-' },
  { code: 'KOR5', title: 'Yu-min Cho', section: 'South Korea', type: '-' },
  { code: 'KOR6', title: 'Young-woo Seol', section: 'South Korea', type: '-' },
  { code: 'KOR7', title: 'Han-beom Lee', section: 'South Korea', type: '-' },
  { code: 'KOR8', title: 'Tae-seok Lee', section: 'South Korea', type: '-' },
  { code: 'KOR9', title: 'Myung-jae Lee', section: 'South Korea', type: '-' },
  { code: 'KOR10', title: 'Jae-sung Lee', section: 'South Korea', type: '-' },
  { code: 'KOR11', title: 'In-beom Hwang', section: 'South Korea', type: '-' },
  { code: 'KOR12', title: 'Kang-in Lee', section: 'South Korea', type: '-' },
  { code: 'KOR13', title: 'Team Photo', section: 'South Korea', type: '-' },
  { code: 'KOR14', title: 'Seung-ho Paik', section: 'South Korea', type: '-' },
  { code: 'KOR15', title: 'Jens Castrop', section: 'South Korea', type: '-' },
  { code: 'KOR16', title: 'Dongg-yeong Lee', section: 'South Korea', type: '-' },
  { code: 'KOR17', title: 'Gue-sung Cho', section: 'South Korea', type: '-' },
  { code: 'KOR18', title: 'Heung-min Son', section: 'South Korea', type: '-' },
  { code: 'KOR19', title: 'Hee-chan Hwang', section: 'South Korea', type: '-' },
  { code: 'KOR20', title: 'Hyeon-Gyu Oh', section: 'South Korea', type: '-' },
  { code: 'CZE1', title: 'Emblem', section: 'Czechia', type: 'foil' },
  { code: 'CZE2', title: 'Matej Kovar', section: 'Czechia', type: '-' },
  { code: 'CZE3', title: 'Jindrich Stanek', section: 'Czechia', type: '-' },
  { code: 'CZE4', title: 'Ladislav Krejci', section: 'Czechia', type: '-' },
  { code: 'CZE5', title: 'Vladimir Coufal', section: 'Czechia', type: '-' },
  { code: 'CZE6', title: 'Jaroslav Zeleny', section: 'Czechia', type: '-' },
  { code: 'CZE7', title: 'Tomas Holes', section: 'Czechia', type: '-' },
  { code: 'CZE8', title: 'David Zima', section: 'Czechia', type: '-' },
  { code: 'CZE9', title: 'Michal Sadilek', section: 'Czechia', type: '-' },
  { code: 'CZE10', title: 'Lukas Provod', section: 'Czechia', type: '-' },
  { code: 'CZE11', title: 'Lukas Cerv', section: 'Czechia', type: '-' },
  { code: 'CZE12', title: 'Tomas Soucek', section: 'Czechia', type: '-' },
  { code: 'CZE13', title: 'Team Photo', section: 'Czechia', type: '-' },
  { code: 'CZE14', title: 'Pavel Sulc', section: 'Czechia', type: '-' },
  { code: 'CZE15', title: 'Matej Vydra', section: 'Czechia', type: '-' },
  { code: 'CZE16', title: 'Vasil Kusej', section: 'Czechia', type: '-' },
  { code: 'CZE17', title: 'Tomas Chory', section: 'Czechia', type: '-' },
  { code: 'CZE18', title: 'Vaclav Cerny', section: 'Czechia', type: '-' },
  { code: 'CZE19', title: 'Adam Hlozek', section: 'Czechia', type: '-' },
  { code: 'CZE20', title: 'Patrik Schick', section: 'Czechia', type: '-' },
  { code: 'CAN1', title: 'Emblem', section: 'Canada', type: 'foil' },
  { code: 'CAN2', title: 'Dayne St.Clair', section: 'Canada', type: '-' },
  { code: 'CAN3', title: 'Alphonso Davies', section: 'Canada', type: '-' },
  { code: 'CAN4', title: 'Alistair Johnston', section: 'Canada', type: '-' },
  { code: 'CAN5', title: 'Samuel Adekugbe', section: 'Canada', type: '-' },
  { code: 'CAN6', title: 'Richie Laryea', section: 'Canada', type: '-' },
  { code: 'CAN7', title: 'Derek Cornelius', section: 'Canada', type: '-' },
  { code: 'CAN8', title: 'Moïse Bombito', section: 'Canada', type: '-' },
  { code: 'CAN9', title: 'Kamal Miller', section: 'Canada', type: '-' },
  { code: 'CAN10', title: 'Stephen Eustáquio', section: 'Canada', type: '-' },
  { code: 'CAN11', title: 'Ismaël Koné', section: 'Canada', type: '-' },
  { code: 'CAN12', title: 'Jonathan Osorio', section: 'Canada', type: '-' },
  { code: 'CAN13', title: 'Team Photo', section: 'Canada', type: '-' },
  { code: 'CAN14', title: 'Jacob Shaffelburg', section: 'Canada', type: '-' },
  { code: 'CAN15', title: 'Mathieu Choinière', section: 'Canada', type: '-' },
  { code: 'CAN16', title: 'Niko Sigur', section: 'Canada', type: '-' },
  { code: 'CAN17', title: 'Tajon Buchanan', section: 'Canada', type: '-' },
  { code: 'CAN18', title: 'Liam Millar', section: 'Canada', type: '-' },
  { code: 'CAN19', title: 'Cyle Larin', section: 'Canada', type: '-' },
  { code: 'CAN20', title: 'Jonathan David', section: 'Canada', type: '-' },
  { code: 'BIH1', title: 'Emblem', section: 'Bosnia and Herzegovina', type: 'foil' },
  { code: 'BIH2', title: 'Nikola Vasilj', section: 'Bosnia and Herzegovina', type: '-' },
  { code: 'BIH3', title: 'Amer Dedic', section: 'Bosnia and Herzegovina', type: '-' },
  { code: 'BIH4', title: 'Sead Kolasinac', section: 'Bosnia and Herzegovina', type: '-' },
  { code: 'BIH5', title: 'Tarik Muharemovic', section: 'Bosnia and Herzegovina', type: '-' },
  { code: 'BIH6', title: 'Nihad Mujakic', section: 'Bosnia and Herzegovina', type: '-' },
  { code: 'BIH7', title: 'Nikola Katic', section: 'Bosnia and Herzegovina', type: '-' },
  { code: 'BIH8', title: 'Amir Hadziahmetovic', section: 'Bosnia and Herzegovina', type: '-' },
  { code: 'BIH9', title: 'Benjamin Tahirovic', section: 'Bosnia and Herzegovina', type: '-' },
  { code: 'BIH10', title: 'Armin Gigovic', section: 'Bosnia and Herzegovina', type: '-' },
  { code: 'BIH11', title: 'Ivan Sunjic', section: 'Bosnia and Herzegovina', type: '-' },
  { code: 'BIH12', title: 'Ivan Basic', section: 'Bosnia and Herzegovina', type: '-' },
  { code: 'BIH13', title: 'Team Photo', section: 'Bosnia and Herzegovina', type: '-' },
  { code: 'BIH14', title: 'Dzenis Burnic', section: 'Bosnia and Herzegovina', type: '-' },
  { code: 'BIH15', title: 'Esmir Bajraktarevic', section: 'Bosnia and Herzegovina', type: '-' },
  { code: 'BIH16', title: 'Amar Memic', section: 'Bosnia and Herzegovina', type: '-' },
  { code: 'BIH17', title: 'Ermedin Demirovic', section: 'Bosnia and Herzegovina', type: '-' },
  { code: 'BIH18', title: 'Edin Dzeko', section: 'Bosnia and Herzegovina', type: '-' },
  { code: 'BIH19', title: 'Samed Bazdar', section: 'Bosnia and Herzegovina', type: '-' },
  { code: 'BIH20', title: 'Haris Tabakovic', section: 'Bosnia and Herzegovina', type: '-' },
  { code: 'QAT1', title: 'Emblem', section: 'Qatar', type: 'foil' },
  { code: 'QAT2', title: 'Meshaal Barsham', section: 'Qatar', type: '-' },
  { code: 'QAT3', title: 'Sultan Albrake', section: 'Qatar', type: '-' },
  { code: 'QAT4', title: 'Lucas Mendes', section: 'Qatar', type: '-' },
  { code: 'QAT5', title: 'Homam Ahmed', section: 'Qatar', type: '-' },
  { code: 'QAT6', title: 'Boualem Khoukhi', section: 'Qatar', type: '-' },
  { code: 'QAT7', title: 'Pedro Miguel', section: 'Qatar', type: '-' },
  { code: 'QAT8', title: 'Tarek Salman', section: 'Qatar', type: '-' },
  { code: 'QAT9', title: 'Mohamed Al-Mannai', section: 'Qatar', type: '-' },
  { code: 'QAT10', title: 'Karim Boudiaf', section: 'Qatar', type: '-' },
  { code: 'QAT11', title: 'Assim Madibo', section: 'Qatar', type: '-' },
  { code: 'QAT12', title: 'Ahmed Fatehi', section: 'Qatar', type: '-' },
  { code: 'QAT13', title: 'Team Photo', section: 'Qatar', type: '-' },
  { code: 'QAT14', title: 'Mohammed Waad', section: 'Qatar', type: '-' },
  { code: 'QAT15', title: 'Abdulaziz Hatem', section: 'Qatar', type: '-' },
  { code: 'QAT16', title: 'Hassan Al-Haydos', section: 'Qatar', type: '-' },
  { code: 'QAT17', title: 'Edmilson Junior', section: 'Qatar', type: '-' },
  { code: 'QAT18', title: 'Akram Hassan Afif', section: 'Qatar', type: '-' },
  { code: 'QAT19', title: 'Ahmed Al Ganehi', section: 'Qatar', type: '-' },
  { code: 'QAT20', title: 'Almoez Ali', section: 'Qatar', type: '-' },
  { code: 'SUI1', title: 'Emblem', section: 'Switzerland', type: 'foil' },
  { code: 'SUI2', title: 'Gregor Kobel', section: 'Switzerland', type: '-' },
  { code: 'SUI3', title: 'Yvon Mvogo', section: 'Switzerland', type: '-' },
  { code: 'SUI4', title: 'Manuel Akanji', section: 'Switzerland', type: '-' },
  { code: 'SUI5', title: 'Ricardo Rodriguez', section: 'Switzerland', type: '-' },
  { code: 'SUI6', title: 'Nico Elvedi', section: 'Switzerland', type: '-' },
  { code: 'SUI7', title: 'Aurèle Amenda', section: 'Switzerland', type: '-' },
  { code: 'SUI8', title: 'Silvan Widmer', section: 'Switzerland', type: '-' },
  { code: 'SUI9', title: 'Granit Xhaka', section: 'Switzerland', type: '-' },
  { code: 'SUI10', title: 'Denis Zakaria', section: 'Switzerland', type: '-' },
  { code: 'SUI11', title: 'Remo Freuler', section: 'Switzerland', type: '-' },
  { code: 'SUI12', title: 'Fabian Rieder', section: 'Switzerland', type: '-' },
  { code: 'SUI13', title: 'Team Photo', section: 'Switzerland', type: '-' },
  { code: 'SUI14', title: 'Ardon Jashari', section: 'Switzerland', type: '-' },
  { code: 'SUI15', title: 'Johan Manzambi', section: 'Switzerland', type: '-' },
  { code: 'SUI16', title: 'Michel Aebischer', section: 'Switzerland', type: '-' },
  { code: 'SUI17', title: 'Breel Embolo', section: 'Switzerland', type: '-' },
  { code: 'SUI18', title: 'Ruben Vargas', section: 'Switzerland', type: '-' },
  { code: 'SUI19', title: 'Dan Ndoye', section: 'Switzerland', type: '-' },
  { code: 'SUI20', title: 'Zeki Amdouni', section: 'Switzerland', type: '-' },
  { code: 'BRA1', title: 'Emblem', section: 'Brazil', type: 'foil' },
  { code: 'BRA2', title: 'Alisson', section: 'Brazil', type: '-' },
  { code: 'BRA3', title: 'Bento', section: 'Brazil', type: '-' },
  { code: 'BRA4', title: 'Marquinhos', section: 'Brazil', type: '-' },
  { code: 'BRA5', title: 'Éder Militão', section: 'Brazil', type: '-' },
  { code: 'BRA6', title: 'Gabriel Magalhães', section: 'Brazil', type: '-' },
  { code: 'BRA7', title: 'Danilo', section: 'Brazil', type: '-' },
  { code: 'BRA8', title: 'Wesley', section: 'Brazil', type: '-' },
  { code: 'BRA9', title: 'Lucas Paquetá', section: 'Brazil', type: '-' },
  { code: 'BRA10', title: 'Casemiro', section: 'Brazil', type: '-' },
  { code: 'BRA11', title: 'Bruno Guimarães', section: 'Brazil', type: '-' },
  { code: 'BRA12', title: 'Luiz Henrique', section: 'Brazil', type: '-' },
  { code: 'BRA13', title: 'Team Photo', section: 'Brazil', type: '-' },
  { code: 'BRA14', title: 'Vinicius Júnior', section: 'Brazil', type: '-' },
  { code: 'BRA15', title: 'Rodrygo', section: 'Brazil', type: '-' },
  { code: 'BRA16', title: 'João Pedro', section: 'Brazil', type: '-' },
  { code: 'BRA17', title: 'Matheus Cunha', section: 'Brazil', type: '-' },
  { code: 'BRA18', title: 'Gabriel Martinelli', section: 'Brazil', type: '-' },
  { code: 'BRA19', title: 'Raphinha', section: 'Brazil', type: '-' },
  { code: 'BRA20', title: 'Estévão', section: 'Brazil', type: '-' },
  { code: 'MAR1', title: 'Emblem', section: 'Morocco', type: 'foil' },
  { code: 'MAR2', title: 'Yassine Bounou', section: 'Morocco', type: '-' },
  { code: 'MAR3', title: 'Munir El Kajoui', section: 'Morocco', type: '-' },
  { code: 'MAR4', title: 'Achraf Hakimi', section: 'Morocco', type: '-' },
  { code: 'MAR5', title: 'Noussair Mazraoui', section: 'Morocco', type: '-' },
  { code: 'MAR6', title: 'Nayef Aguerd', section: 'Morocco', type: '-' },
  { code: 'MAR7', title: 'Romain Saïss', section: 'Morocco', type: '-' },
  { code: 'MAR8', title: 'Jawad El Yamiq', section: 'Morocco', type: '-' },
  { code: 'MAR9', title: 'Adam Masina', section: 'Morocco', type: '-' },
  { code: 'MAR10', title: 'Sofyan Amrabat', section: 'Morocco', type: '-' },
  { code: 'MAR11', title: 'Azzedine Ounahi', section: 'Morocco', type: '-' },
  { code: 'MAR12', title: 'Eliesse Ben Seghir', section: 'Morocco', type: '-' },
  { code: 'MAR13', title: 'Team Photo', section: 'Morocco', type: '-' },
  { code: 'MAR14', title: 'Bilal El Khannouss', section: 'Morocco', type: '-' },
  { code: 'MAR15', title: 'Ismael Saibari', section: 'Morocco', type: '-' },
  { code: 'MAR16', title: 'Youssef En-Nesyri', section: 'Morocco', type: '-' },
  { code: 'MAR17', title: 'Abde Ezzalzouli', section: 'Morocco', type: '-' },
  { code: 'MAR18', title: 'Soufiane Rahimi', section: 'Morocco', type: '-' },
  { code: 'MAR19', title: 'Brahim Diaz', section: 'Morocco', type: '-' },
  { code: 'MAR20', title: 'Ayoub El Kaabi', section: 'Morocco', type: '-' },
  { code: 'HAI1', title: 'Emblem', section: 'Haiti', type: 'foil' },
  { code: 'HAI2', title: 'Johny Placide', section: 'Haiti', type: '-' },
  { code: 'HAI3', title: 'Carlens Arcus', section: 'Haiti', type: '-' },
  { code: 'HAI4', title: 'Martin Expérience', section: 'Haiti', type: '-' },
  { code: 'HAI5', title: 'Jean-Kevin Duverne', section: 'Haiti', type: '-' },
  { code: 'HAI6', title: 'Ricardo Adé', section: 'Haiti', type: '-' },
  { code: 'HAI7', title: 'Duke Lacroix', section: 'Haiti', type: '-' },
  { code: 'HAI8', title: 'Garven Metusala', section: 'Haiti', type: '-' },
  { code: 'HAI9', title: 'Hannes Delcroix', section: 'Haiti', type: '-' },
  { code: 'HAI10', title: 'Leverton Pierre', section: 'Haiti', type: '-' },
  { code: 'HAI11', title: 'Danley Jean Jacques', section: 'Haiti', type: '-' },
  { code: 'HAI12', title: 'Jean-Ricner Bellegarde', section: 'Haiti', type: '-' },
  { code: 'HAI13', title: 'Team Photo', section: 'Haiti', type: '-' },
  { code: 'HAI14', title: 'Christopher Attys', section: 'Haiti', type: '-' },
  { code: 'HAI15', title: 'Derrick Etienne Jr', section: 'Haiti', type: '-' },
  { code: 'HAI16', title: 'Josue Casimir', section: 'Haiti', type: '-' },
  { code: 'HAI17', title: 'Ruben Providence', section: 'Haiti', type: '-' },
  { code: 'HAI18', title: 'Duckens Nazon', section: 'Haiti', type: '-' },
  { code: 'HAI19', title: 'Louicius Deedson', section: 'Haiti', type: '-' },
  { code: 'HAI20', title: 'Frantzdy Pierrot', section: 'Haiti', type: '-' },
  { code: 'SCO1', title: 'Emblem', section: 'Scotland', type: 'foil' },
  { code: 'SCO2', title: 'Angus Gunn', section: 'Scotland', type: '-' },
  { code: 'SCO3', title: 'Jack Hendry', section: 'Scotland', type: '-' },
  { code: 'SCO4', title: 'Kieran Tierney', section: 'Scotland', type: '-' },
  { code: 'SCO5', title: 'Aaron Hickey', section: 'Scotland', type: '-' },
  { code: 'SCO6', title: 'Andrew Robertson', section: 'Scotland', type: '-' },
  { code: 'SCO7', title: 'Scott McKenna', section: 'Scotland', type: '-' },
  { code: 'SCO8', title: 'John Souttar', section: 'Scotland', type: '-' },
  { code: 'SCO9', title: 'Anthony Ralston', section: 'Scotland', type: '-' },
  { code: 'SCO10', title: 'Grant Hanley', section: 'Scotland', type: '-' },
  { code: 'SCO11', title: 'Scott McTominay', section: 'Scotland', type: '-' },
  { code: 'SCO12', title: 'Billy Gilmour', section: 'Scotland', type: '-' },
  { code: 'SCO13', title: 'Team Photo', section: 'Scotland', type: '-' },
  { code: 'SCO14', title: 'Lewis Ferguson', section: 'Scotland', type: '-' },
  { code: 'SCO15', title: 'Ryan Christie', section: 'Scotland', type: '-' },
  { code: 'SCO16', title: 'Kenny McLean', section: 'Scotland', type: '-' },
  { code: 'SCO17', title: 'John McGinn', section: 'Scotland', type: '-' },
  { code: 'SCO18', title: 'Lyndon Dykes', section: 'Scotland', type: '-' },
  { code: 'SCO19', title: 'Che Adams', section: 'Scotland', type: '-' },
  { code: 'SCO20', title: 'Ben Gannon-Doak', section: 'Scotland', type: '-' },
  { code: 'USA1', title: 'Emblem', section: 'USA', type: 'foil' },
  { code: 'USA2', title: 'Matt Freese', section: 'USA', type: '-' },
  { code: 'USA3', title: 'Chris Richards', section: 'USA', type: '-' },
  { code: 'USA4', title: 'Tim Ream', section: 'USA', type: '-' },
  { code: 'USA5', title: 'Mark McKenzie', section: 'USA', type: '-' },
  { code: 'USA6', title: 'Alex Freeman', section: 'USA', type: '-' },
  { code: 'USA7', title: 'Antonee Robinson', section: 'USA', type: '-' },
  { code: 'USA8', title: 'Tyler Adams', section: 'USA', type: '-' },
  { code: 'USA9', title: 'Tanner Tessmann', section: 'USA', type: '-' },
  { code: 'USA10', title: 'Weston McKenny', section: 'USA', type: '-' },
  { code: 'USA11', title: 'Christian Roldan', section: 'USA', type: '-' },
  { code: 'USA12', title: 'Timothy Weah', section: 'USA', type: '-' },
  { code: 'USA13', title: 'Team Photo', section: 'USA', type: '-' },
  { code: 'USA14', title: 'Diego Luna', section: 'USA', type: '-' },
  { code: 'USA15', title: 'Malik Tillman', section: 'USA', type: '-' },
  { code: 'USA16', title: 'Christian Pulisic', section: 'USA', type: '-' },
  { code: 'USA17', title: 'Brenden Aaronson', section: 'USA', type: '-' },
  { code: 'USA18', title: 'Ricardo Pepi', section: 'USA', type: '-' },
  { code: 'USA19', title: 'Haji Wright', section: 'USA', type: '-' },
  { code: 'USA20', title: 'Folarin Balogun', section: 'USA', type: '-' },
  { code: 'PAR1', title: 'Emblem', section: 'Paraguay', type: 'foil' },
  { code: 'PAR2', title: 'Roberto Fernandez', section: 'Paraguay', type: '-' },
  { code: 'PAR3', title: 'Orlando Gill', section: 'Paraguay', type: '-' },
  { code: 'PAR4', title: 'Gustavo Gomez', section: 'Paraguay', type: '-' },
  { code: 'PAR5', title: 'Fabián Balbuena', section: 'Paraguay', type: '-' },
  { code: 'PAR6', title: 'Juan José Cáceres', section: 'Paraguay', type: '-' },
  { code: 'PAR7', title: 'Omar Alderete', section: 'Paraguay', type: '-' },
  { code: 'PAR8', title: 'Junior Alonso', section: 'Paraguay', type: '-' },
  { code: 'PAR9', title: 'Mathías Villasanti', section: 'Paraguay', type: '-' },
  { code: 'PAR10', title: 'Diego Gomez', section: 'Paraguay', type: '-' },
  { code: 'PAR11', title: 'Damián Bobadilla', section: 'Paraguay', type: '-' },
  { code: 'PAR12', title: 'Andres Cubas', section: 'Paraguay', type: '-' },
  { code: 'PAR13', title: 'Team Photo', section: 'Paraguay', type: '-' },
  { code: 'PAR14', title: 'Matias Galarza Fonda', section: 'Paraguay', type: '-' },
  { code: 'PAR15', title: 'Julio Enciso', section: 'Paraguay', type: '-' },
  { code: 'PAR16', title: 'Alejandro Romero Gamarra', section: 'Paraguay', type: '-' },
  { code: 'PAR17', title: 'Miguel Almirón', section: 'Paraguay', type: '-' },
  { code: 'PAR18', title: 'Ramon Sosa', section: 'Paraguay', type: '-' },
  { code: 'PAR19', title: 'Angel Romero', section: 'Paraguay', type: '-' },
  { code: 'PAR20', title: 'Antonio Sanabria', section: 'Paraguay', type: '-' },
  { code: 'AUS1', title: 'Emblem', section: 'Australia', type: 'foil' },
  { code: 'AUS2', title: 'Mathew Ryan', section: 'Australia', type: '-' },
  { code: 'AUS3', title: 'Joe Gauci', section: 'Australia', type: '-' },
  { code: 'AUS4', title: 'Harry Souttar', section: 'Australia', type: '-' },
  { code: 'AUS5', title: 'Alessandro Circati', section: 'Australia', type: '-' },
  { code: 'AUS6', title: 'Jordan Bos', section: 'Australia', type: '-' },
  { code: 'AUS7', title: 'Aziz Behich', section: 'Australia', type: '-' },
  { code: 'AUS8', title: 'Cameron Burgess', section: 'Australia', type: '-' },
  { code: 'AUS9', title: 'Lewis Miller', section: 'Australia', type: '-' },
  { code: 'AUS10', title: 'Milos Degenek', section: 'Australia', type: '-' },
  { code: 'AUS11', title: 'Jackson Irvine', section: 'Australia', type: '-' },
  { code: 'AUS12', title: 'Riley McGree', section: 'Australia', type: '-' },
  { code: 'AUS13', title: 'Team Photo', section: 'Australia', type: '-' },
  { code: 'AUS14', title: 'Aiden O\'Neill', section: 'Australia', type: '-' },
  { code: 'AUS15', title: 'Connor Metcalfe', section: 'Australia', type: '-' },
  { code: 'AUS16', title: 'Patrick Yazbek', section: 'Australia', type: '-' },
  { code: 'AUS17', title: 'Craig Goodwin', section: 'Australia', type: '-' },
  { code: 'AUS18', title: 'Kusini Yengi', section: 'Australia', type: '-' },
  { code: 'AUS19', title: 'Nestory Irankunda', section: 'Australia', type: '-' },
  { code: 'AUS20', title: 'Mohamed Touré', section: 'Australia', type: '-' },
  { code: 'TUR1', title: 'Emblem', section: 'Türkiye', type: 'foil' },
  { code: 'TUR2', title: 'Ugurcan Cakir', section: 'Türkiye', type: '-' },
  { code: 'TUR3', title: 'Mert Muldur', section: 'Türkiye', type: '-' },
  { code: 'TUR4', title: 'Zeki Celik', section: 'Türkiye', type: '-' },
  { code: 'TUR5', title: 'Abdulkerim Bardakci', section: 'Türkiye', type: '-' },
  { code: 'TUR6', title: 'Caglar Soyuncu', section: 'Türkiye', type: '-' },
  { code: 'TUR7', title: 'Merih Demiral', section: 'Türkiye', type: '-' },
  { code: 'TUR8', title: 'Ferdi Kadioglu', section: 'Türkiye', type: '-' },
  { code: 'TUR9', title: 'Kaan Ayhan', section: 'Türkiye', type: '-' },
  { code: 'TUR10', title: 'Ismail Yuksek', section: 'Türkiye', type: '-' },
  { code: 'TUR11', title: 'Hakan Calhanoglu', section: 'Türkiye', type: '-' },
  { code: 'TUR12', title: 'Orkun Kokcu', section: 'Türkiye', type: '-' },
  { code: 'TUR13', title: 'Team Photo', section: 'Türkiye', type: '-' },
  { code: 'TUR14', title: 'Arda Guler', section: 'Türkiye', type: '-' },
  { code: 'TUR15', title: 'Irfan Can Kahveci', section: 'Türkiye', type: '-' },
  { code: 'TUR16', title: 'Yunus Akgun', section: 'Türkiye', type: '-' },
  { code: 'TUR17', title: 'Can Uzun', section: 'Türkiye', type: '-' },
  { code: 'TUR18', title: 'Baris Alper Yilmaz', section: 'Türkiye', type: '-' },
  { code: 'TUR19', title: 'Kerem Akturkoglu', section: 'Türkiye', type: '-' },
  { code: 'TUR20', title: 'Kenan Yildiz', section: 'Türkiye', type: '-' },
  { code: 'GER1', title: 'Emblem', section: 'Germany', type: 'foil' },
  { code: 'GER2', title: 'Marc-André ter Stegen', section: 'Germany', type: '-' },
  { code: 'GER3', title: 'Jonathan Tah', section: 'Germany', type: '-' },
  { code: 'GER4', title: 'David Raum', section: 'Germany', type: '-' },
  { code: 'GER5', title: 'Nico Schlotterbeck', section: 'Germany', type: '-' },
  { code: 'GER6', title: 'Antonio Rüdiger', section: 'Germany', type: '-' },
  { code: 'GER7', title: 'Waldemar Anton', section: 'Germany', type: '-' },
  { code: 'GER8', title: 'Ridle Baku', section: 'Germany', type: '-' },
  { code: 'GER9', title: 'Maximilian Mittelstadt', section: 'Germany', type: '-' },
  { code: 'GER10', title: 'Joshua Kimmich', section: 'Germany', type: '-' },
  { code: 'GER11', title: 'Florian Wirtz', section: 'Germany', type: '-' },
  { code: 'GER12', title: 'Felix Nmecha', section: 'Germany', type: '-' },
  { code: 'GER13', title: 'Team Photo', section: 'Germany', type: '-' },
  { code: 'GER14', title: 'Leon Goretzka', section: 'Germany', type: '-' },
  { code: 'GER15', title: 'Jamal Musiala', section: 'Germany', type: '-' },
  { code: 'GER16', title: 'Serge Gnabry', section: 'Germany', type: '-' },
  { code: 'GER17', title: 'Kai Havertz', section: 'Germany', type: '-' },
  { code: 'GER18', title: 'Leroy Sane', section: 'Germany', type: '-' },
  { code: 'GER19', title: 'Karim Adeyemi', section: 'Germany', type: '-' },
  { code: 'GER20', title: 'Nick Woltemade', section: 'Germany', type: '-' },
  { code: 'CUW1', title: 'Emblem', section: 'Curaçao', type: 'foil' },
  { code: 'CUW2', title: 'Eloy Room', section: 'Curaçao', type: '-' },
  { code: 'CUW3', title: 'Armando Obispo', section: 'Curaçao', type: '-' },
  { code: 'CUW4', title: 'Sherel Floranus', section: 'Curaçao', type: '-' },
  { code: 'CUW5', title: 'Jurien Gaari', section: 'Curaçao', type: '-' },
  { code: 'CUW6', title: 'Joshua Brenet', section: 'Curaçao', type: '-' },
  { code: 'CUW7', title: 'Roshon Van Eijma', section: 'Curaçao', type: '-' },
  { code: 'CUW8', title: 'Shurandy Sambo', section: 'Curaçao', type: '-' },
  { code: 'CUW9', title: 'Livano Comenencia', section: 'Curaçao', type: '-' },
  { code: 'CUW10', title: 'Godfried Roemeratoe', section: 'Curaçao', type: '-' },
  { code: 'CUW11', title: 'Juninho Bacuna', section: 'Curaçao', type: '-' },
  { code: 'CUW12', title: 'Leandro Bacuna', section: 'Curaçao', type: '-' },
  { code: 'CUW13', title: 'Team Photo', section: 'Curaçao', type: '-' },
  { code: 'CUW14', title: 'Tahith Chong', section: 'Curaçao', type: '-' },
  { code: 'CUW15', title: 'Kenji Gorre', section: 'Curaçao', type: '-' },
  { code: 'CUW16', title: 'Jearl Margaritha', section: 'Curaçao', type: '-' },
  { code: 'CUW17', title: 'Jurgen Locadia', section: 'Curaçao', type: '-' },
  { code: 'CUW18', title: 'Jeremy Antonisse', section: 'Curaçao', type: '-' },
  { code: 'CUW19', title: 'Gervane Kastaneer', section: 'Curaçao', type: '-' },
  { code: 'CUW20', title: 'Sontje Hansen', section: 'Curaçao', type: '-' },
  { code: 'CIV1', title: 'Emblem', section: 'Ivory Coast', type: 'foil' },
  { code: 'CIV2', title: 'Yahia Fofana', section: 'Ivory Coast', type: '-' },
  { code: 'CIV3', title: 'Ghislain Konan', section: 'Ivory Coast', type: '-' },
  { code: 'CIV4', title: 'Wilfried Singo', section: 'Ivory Coast', type: '-' },
  { code: 'CIV5', title: 'Odilon Kossounou', section: 'Ivory Coast', type: '-' },
  { code: 'CIV6', title: 'Evan Ndicka', section: 'Ivory Coast', type: '-' },
  { code: 'CIV7', title: 'Willy Boly', section: 'Ivory Coast', type: '-' },
  { code: 'CIV8', title: 'Emmanuel Agbadou', section: 'Ivory Coast', type: '-' },
  { code: 'CIV9', title: 'Ousmane Diomande', section: 'Ivory Coast', type: '-' },
  { code: 'CIV10', title: 'Franck Kessie', section: 'Ivory Coast', type: '-' },
  { code: 'CIV11', title: 'Seko Fofana', section: 'Ivory Coast', type: '-' },
  { code: 'CIV12', title: 'Ibrahim Sangare', section: 'Ivory Coast', type: '-' },
  { code: 'CIV13', title: 'Team Photo', section: 'Ivory Coast', type: '-' },
  { code: 'CIV14', title: 'Jean-Philippe Gbamin', section: 'Ivory Coast', type: '-' },
  { code: 'CIV15', title: 'Amad Diallo', section: 'Ivory Coast', type: '-' },
  { code: 'CIV16', title: 'Sébastien Haller', section: 'Ivory Coast', type: '-' },
  { code: 'CIV17', title: 'Simon Adingra', section: 'Ivory Coast', type: '-' },
  { code: 'CIV18', title: 'Yan Diomande', section: 'Ivory Coast', type: '-' },
  { code: 'CIV19', title: 'Evann Guessand', section: 'Ivory Coast', type: '-' },
  { code: 'CIV20', title: 'Oumar Diakite', section: 'Ivory Coast', type: '-' },
  { code: 'ECU1', title: 'Emblem', section: 'Ecuador', type: 'foil' },
  { code: 'ECU2', title: 'Hernán Galíndez', section: 'Ecuador', type: '-' },
  { code: 'ECU3', title: 'Gonzalo Valle', section: 'Ecuador', type: '-' },
  { code: 'ECU4', title: 'Piero Hincapié', section: 'Ecuador', type: '-' },
  { code: 'ECU5', title: 'Pervis Estupiñán', section: 'Ecuador', type: '-' },
  { code: 'ECU6', title: 'Willian Pacho', section: 'Ecuador', type: '-' },
  { code: 'ECU7', title: 'Ángelo Preciado', section: 'Ecuador', type: '-' },
  { code: 'ECU8', title: 'Joel Ordóñez', section: 'Ecuador', type: '-' },
  { code: 'ECU9', title: 'Moises Caicedo', section: 'Ecuador', type: '-' },
  { code: 'ECU10', title: 'Alan Franco', section: 'Ecuador', type: '-' },
  { code: 'ECU11', title: 'Kendry Paez', section: 'Ecuador', type: '-' },
  { code: 'ECU12', title: 'Pedro Vite', section: 'Ecuador', type: '-' },
  { code: 'ECU13', title: 'Team Photo', section: 'Ecuador', type: '-' },
  { code: 'ECU14', title: 'John Yeboah', section: 'Ecuador', type: '-' },
  { code: 'ECU15', title: 'Leonardo Campana', section: 'Ecuador', type: '-' },
  { code: 'ECU16', title: 'Gonzalo Plata', section: 'Ecuador', type: '-' },
  { code: 'ECU17', title: 'Nilson Angulo', section: 'Ecuador', type: '-' },
  { code: 'ECU18', title: 'Alan Minda', section: 'Ecuador', type: '-' },
  { code: 'ECU19', title: 'Kevin Rodriguez', section: 'Ecuador', type: '-' },
  { code: 'ECU20', title: 'Enner Valencia', section: 'Ecuador', type: '-' },
  { code: 'NED1', title: 'Emblem', section: 'Netherlands', type: 'foil' },
  { code: 'NED2', title: 'Bart Verbruggen', section: 'Netherlands', type: '-' },
  { code: 'NED3', title: 'Virgil van Dijk', section: 'Netherlands', type: '-' },
  { code: 'NED4', title: 'Micky van de Ven', section: 'Netherlands', type: '-' },
  { code: 'NED5', title: 'Jurrien Timber', section: 'Netherlands', type: '-' },
  { code: 'NED6', title: 'Denzel Dumfries', section: 'Netherlands', type: '-' },
  { code: 'NED7', title: 'Nathan Aké', section: 'Netherlands', type: '-' },
  { code: 'NED8', title: 'Jeremie Frimpong', section: 'Netherlands', type: '-' },
  { code: 'NED9', title: 'Jan Paul van Hecke', section: 'Netherlands', type: '-' },
  { code: 'NED10', title: 'Tijjani Reijnders', section: 'Netherlands', type: '-' },
  { code: 'NED11', title: 'Ryan Gravenberch', section: 'Netherlands', type: '-' },
  { code: 'NED12', title: 'Teun Koopmeiners', section: 'Netherlands', type: '-' },
  { code: 'NED13', title: 'Team Photo', section: 'Netherlands', type: '-' },
  { code: 'NED14', title: 'Frenkie de Jong', section: 'Netherlands', type: '-' },
  { code: 'NED15', title: 'Xavi Simons', section: 'Netherlands', type: '-' },
  { code: 'NED16', title: 'Justin Kluivert', section: 'Netherlands', type: '-' },
  { code: 'NED17', title: 'Memphis Depay', section: 'Netherlands', type: '-' },
  { code: 'NED18', title: 'Donyell Malen', section: 'Netherlands', type: '-' },
  { code: 'NED19', title: 'Wout Weghorst', section: 'Netherlands', type: '-' },
  { code: 'NED20', title: 'Cody Gakpo', section: 'Netherlands', type: '-' },
  { code: 'JPN1', title: 'Emblem', section: 'Japan', type: 'foil' },
  { code: 'JPN2', title: 'Zion Suzuki', section: 'Japan', type: '-' },
  { code: 'JPN3', title: 'Henry Heroki Mochizuki', section: 'Japan', type: '-' },
  { code: 'JPN4', title: 'Ayumu Seko', section: 'Japan', type: '-' },
  { code: 'JPN5', title: 'Junnosuke Suzuki', section: 'Japan', type: '-' },
  { code: 'JPN6', title: 'Shogo Taniguchi', section: 'Japan', type: '-' },
  { code: 'JPN7', title: 'Tsuyoshi Watanabe', section: 'Japan', type: '-' },
  { code: 'JPN8', title: 'Kaishu Sano', section: 'Japan', type: '-' },
  { code: 'JPN9', title: 'Yuki Soma', section: 'Japan', type: '-' },
  { code: 'JPN10', title: 'Ao Tanaka', section: 'Japan', type: '-' },
  { code: 'JPN11', title: 'Daichi Kamada', section: 'Japan', type: '-' },
  { code: 'JPN12', title: 'Takefusa Kubo', section: 'Japan', type: '-' },
  { code: 'JPN13', title: 'Team Photo', section: 'Japan', type: '-' },
  { code: 'JPN14', title: 'Ritsu Doan', section: 'Japan', type: '-' },
  { code: 'JPN15', title: 'Keito Nakamura', section: 'Japan', type: '-' },
  { code: 'JPN16', title: 'Takumi Minamino', section: 'Japan', type: '-' },
  { code: 'JPN17', title: 'Shuto Machino', section: 'Japan', type: '-' },
  { code: 'JPN18', title: 'Junya Ito', section: 'Japan', type: '-' },
  { code: 'JPN19', title: 'Koki Ogawa', section: 'Japan', type: '-' },
  { code: 'JPN20', title: 'Ayase Ueda', section: 'Japan', type: '-' },
  { code: 'SWE1', title: 'Emblem', section: 'Sweden', type: 'foil' },
  { code: 'SWE2', title: 'Victor Johansson', section: 'Sweden', type: '-' },
  { code: 'SWE3', title: 'Isak Hien', section: 'Sweden', type: '-' },
  { code: 'SWE4', title: 'Gabriel Gudmundsson', section: 'Sweden', type: '-' },
  { code: 'SWE5', title: 'Emil Holm', section: 'Sweden', type: '-' },
  { code: 'SWE6', title: 'Victor Nilsson Lindelöf', section: 'Sweden', type: '-' },
  { code: 'SWE7', title: 'Gustaf Lagerbielke', section: 'Sweden', type: '-' },
  { code: 'SWE8', title: 'Lucas Bergvall', section: 'Sweden', type: '-' },
  { code: 'SWE9', title: 'Hugo Larsson', section: 'Sweden', type: '-' },
  { code: 'SWE10', title: 'Jesper Karlström', section: 'Sweden', type: '-' },
  { code: 'SWE11', title: 'Yasin Ayari', section: 'Sweden', type: '-' },
  { code: 'SWE12', title: 'Mattias Svanberg', section: 'Sweden', type: '-' },
  { code: 'SWE13', title: 'Team Photo', section: 'Sweden', type: '-' },
  { code: 'SWE14', title: 'Daniel Svensson', section: 'Sweden', type: '-' },
  { code: 'SWE15', title: 'Ken Sema', section: 'Sweden', type: '-' },
  { code: 'SWE16', title: 'Roony Bardghji', section: 'Sweden', type: '-' },
  { code: 'SWE17', title: 'Dejan Kulusevski', section: 'Sweden', type: '-' },
  { code: 'SWE18', title: 'Anthony Elanga', section: 'Sweden', type: '-' },
  { code: 'SWE19', title: 'Alexander Isak', section: 'Sweden', type: '-' },
  { code: 'SWE20', title: 'Viktor Gyökeres', section: 'Sweden', type: '-' },
  { code: 'TUN1', title: 'Emblem', section: 'Tunisia', type: 'foil' },
  { code: 'TUN2', title: 'Bechir Ben Said', section: 'Tunisia', type: '-' },
  { code: 'TUN3', title: 'Aymen Dahmen', section: 'Tunisia', type: '-' },
  { code: 'TUN4', title: 'Yan Valery', section: 'Tunisia', type: '-' },
  { code: 'TUN5', title: 'Montassar Talbi', section: 'Tunisia', type: '-' },
  { code: 'TUN6', title: 'Yassine Meriah', section: 'Tunisia', type: '-' },
  { code: 'TUN7', title: 'Ali Abdi', section: 'Tunisia', type: '-' },
  { code: 'TUN8', title: 'Dylan Bronn', section: 'Tunisia', type: '-' },
  { code: 'TUN9', title: 'Ellyes Skhiri', section: 'Tunisia', type: '-' },
  { code: 'TUN10', title: 'Aissa Laidouni', section: 'Tunisia', type: '-' },
  { code: 'TUN11', title: 'Ferjani Sassi', section: 'Tunisia', type: '-' },
  { code: 'TUN12', title: 'Mohamed Ali Ben Romdhane', section: 'Tunisia', type: '-' },
  { code: 'TUN13', title: 'Team Photo', section: 'Tunisia', type: '-' },
  { code: 'TUN14', title: 'Hannibal Mejbri', section: 'Tunisia', type: '-' },
  { code: 'TUN15', title: 'Elias Achouri', section: 'Tunisia', type: '-' },
  { code: 'TUN16', title: 'Elias Saad', section: 'Tunisia', type: '-' },
  { code: 'TUN17', title: 'Hazem Mastouri', section: 'Tunisia', type: '-' },
  { code: 'TUN18', title: 'Ismael Gharbi', section: 'Tunisia', type: '-' },
  { code: 'TUN19', title: 'Sayfallah Ltaief', section: 'Tunisia', type: '-' },
  { code: 'TUN20', title: 'Naim Sliti', section: 'Tunisia', type: '-' },
  { code: 'BEL1', title: 'Emblem', section: 'Belgium', type: 'foil' },
  { code: 'BEL2', title: 'Thibaut Courtois', section: 'Belgium', type: '-' },
  { code: 'BEL3', title: 'Arthur Theate', section: 'Belgium', type: '-' },
  { code: 'BEL4', title: 'Timothy Castagne', section: 'Belgium', type: '-' },
  { code: 'BEL5', title: 'Zeno Debast', section: 'Belgium', type: '-' },
  { code: 'BEL6', title: 'Brandon Mechele', section: 'Belgium', type: '-' },
  { code: 'BEL7', title: 'Maxim De Cuyper', section: 'Belgium', type: '-' },
  { code: 'BEL8', title: 'Thomas Meunier', section: 'Belgium', type: '-' },
  { code: 'BEL9', title: 'Youri Tielemans', section: 'Belgium', type: '-' },
  { code: 'BEL10', title: 'Amadou Onana', section: 'Belgium', type: '-' },
  { code: 'BEL11', title: 'Nicolas Raskin', section: 'Belgium', type: '-' },
  { code: 'BEL12', title: 'Alexis Saelemaekers', section: 'Belgium', type: '-' },
  { code: 'BEL13', title: 'Team Photo', section: 'Belgium', type: '-' },
  { code: 'BEL14', title: 'Hans Vanaken', section: 'Belgium', type: '-' },
  { code: 'BEL15', title: 'Kevin De Bruyne', section: 'Belgium', type: '-' },
  { code: 'BEL16', title: 'Jérémy Doku', section: 'Belgium', type: '-' },
  { code: 'BEL17', title: 'Charles De Ketelaere', section: 'Belgium', type: '-' },
  { code: 'BEL18', title: 'Leandro Trossard', section: 'Belgium', type: '-' },
  { code: 'BEL19', title: 'Loïs Openda', section: 'Belgium', type: '-' },
  { code: 'BEL20', title: 'Romelu Lukaku', section: 'Belgium', type: '-' },
  { code: 'EGY1', title: 'Emblem', section: 'Egypt', type: 'foil' },
  { code: 'EGY2', title: 'Mohamed El Shenawy', section: 'Egypt', type: '-' },
  { code: 'EGY3', title: 'Mohamed Hany', section: 'Egypt', type: '-' },
  { code: 'EGY4', title: 'Mohamed Hamdy', section: 'Egypt', type: '-' },
  { code: 'EGY5', title: 'Yasser Ibrahim', section: 'Egypt', type: '-' },
  { code: 'EGY6', title: 'Khaled Sobhi', section: 'Egypt', type: '-' },
  { code: 'EGY7', title: 'Ramy Rabia', section: 'Egypt', type: '-' },
  { code: 'EGY8', title: 'Hossam Abdelmaguid', section: 'Egypt', type: '-' },
  { code: 'EGY9', title: 'Ahmed Fatouh', section: 'Egypt', type: '-' },
  { code: 'EGY10', title: 'Marwan Attia', section: 'Egypt', type: '-' },
  { code: 'EGY11', title: 'Zizo', section: 'Egypt', type: '-' },
  { code: 'EGY12', title: 'Hamdy Fathy', section: 'Egypt', type: '-' },
  { code: 'EGY13', title: 'Team Photo', section: 'Egypt', type: '-' },
  { code: 'EGY14', title: 'Mohamed Lasheen', section: 'Egypt', type: '-' },
  { code: 'EGY15', title: 'Emam Ashour', section: 'Egypt', type: '-' },
  { code: 'EGY16', title: 'Osama Faisal', section: 'Egypt', type: '-' },
  { code: 'EGY17', title: 'Mohamed Salah', section: 'Egypt', type: '-' },
  { code: 'EGY18', title: 'Mostafa Mohamed', section: 'Egypt', type: '-' },
  { code: 'EGY19', title: 'Trezeguet', section: 'Egypt', type: '-' },
  { code: 'EGY20', title: 'Omar Marmoush', section: 'Egypt', type: '-' },
  { code: 'IRN1', title: 'Emblem', section: 'Iran', type: 'foil' },
  { code: 'IRN2', title: 'Alireza Beiranvand', section: 'Iran', type: '-' },
  { code: 'IRN3', title: 'Morteza Pouraliganji', section: 'Iran', type: '-' },
  { code: 'IRN4', title: 'Ehsan Hajsafi', section: 'Iran', type: '-' },
  { code: 'IRN5', title: 'Milad Mohammadi', section: 'Iran', type: '-' },
  { code: 'IRN6', title: 'Shojae Khalilzadeh', section: 'Iran', type: '-' },
  { code: 'IRN7', title: 'Ramin Rezaeian', section: 'Iran', type: '-' },
  { code: 'IRN8', title: 'Hossein Kanaani', section: 'Iran', type: '-' },
  { code: 'IRN9', title: 'Sadegh Moharrami', section: 'Iran', type: '-' },
  { code: 'IRN10', title: 'Saleh Hardani', section: 'Iran', type: '-' },
  { code: 'IRN11', title: 'Saeed Ezatolahi', section: 'Iran', type: '-' },
  { code: 'IRN12', title: 'Saman Ghoddos', section: 'Iran', type: '-' },
  { code: 'IRN13', title: 'Team Photo', section: 'Iran', type: '-' },
  { code: 'IRN14', title: 'Omid Noorafkan', section: 'Iran', type: '-' },
  { code: 'IRN15', title: 'Roozbeh Cheshmi', section: 'Iran', type: '-' },
  { code: 'IRN16', title: 'Mohammad Mohebi', section: 'Iran', type: '-' },
  { code: 'IRN17', title: 'Sardar Azmoun', section: 'Iran', type: '-' },
  { code: 'IRN18', title: 'Mehdi Taremi', section: 'Iran', type: '-' },
  { code: 'IRN19', title: 'Alireza Jahanbakhsh', section: 'Iran', type: '-' },
  { code: 'IRN20', title: 'Ali Gholizadeh', section: 'Iran', type: '-' },
  { code: 'NZL1', title: 'Emblem', section: 'New Zealand', type: 'foil' },
  { code: 'NZL2', title: 'Max Crocombe', section: 'New Zealand', type: '-' },
  { code: 'NZL3', title: 'Alex Paulsen', section: 'New Zealand', type: '-' },
  { code: 'NZL4', title: 'Michael Boxall', section: 'New Zealand', type: '-' },
  { code: 'NZL5', title: 'Liberato Cacace', section: 'New Zealand', type: '-' },
  { code: 'NZL6', title: 'Tim Payne', section: 'New Zealand', type: '-' },
  { code: 'NZL7', title: 'Tyler Bindon', section: 'New Zealand', type: '-' },
  { code: 'NZL8', title: 'Francis de Vries', section: 'New Zealand', type: '-' },
  { code: 'NZL9', title: 'Finn Surman', section: 'New Zealand', type: '-' },
  { code: 'NZL10', title: 'Joe Bell', section: 'New Zealand', type: '-' },
  { code: 'NZL11', title: 'Sarpreet Singh', section: 'New Zealand', type: '-' },
  { code: 'NZL12', title: 'Ryan Thomas', section: 'New Zealand', type: '-' },
  { code: 'NZL13', title: 'Team Photo', section: 'New Zealand', type: '-' },
  { code: 'NZL14', title: 'Matthew Garbett', section: 'New Zealand', type: '-' },
  { code: 'NZL15', title: 'Marko Stamenić', section: 'New Zealand', type: '-' },
  { code: 'NZL16', title: 'Ben Old', section: 'New Zealand', type: '-' },
  { code: 'NZL17', title: 'Chris Wood', section: 'New Zealand', type: '-' },
  { code: 'NZL18', title: 'Elijah Just', section: 'New Zealand', type: '-' },
  { code: 'NZL19', title: 'Callum McCowatt', section: 'New Zealand', type: '-' },
  { code: 'NZL20', title: 'Kosta Barbarouses', section: 'New Zealand', type: '-' },
  { code: 'ESP1', title: 'Emblem', section: 'Spain', type: 'foil' },
  { code: 'ESP2', title: 'Unai Simon', section: 'Spain', type: '-' },
  { code: 'ESP3', title: 'Robin Le Normand', section: 'Spain', type: '-' },
  { code: 'ESP4', title: 'Aymeric Laporte', section: 'Spain', type: '-' },
  { code: 'ESP5', title: 'Dean Huijsen', section: 'Spain', type: '-' },
  { code: 'ESP6', title: 'Pedro Porro', section: 'Spain', type: '-' },
  { code: 'ESP7', title: 'Dani Carvajal', section: 'Spain', type: '-' },
  { code: 'ESP8', title: 'Marc Cucurella', section: 'Spain', type: '-' },
  { code: 'ESP9', title: 'Martín Zubimendi', section: 'Spain', type: '-' },
  { code: 'ESP10', title: 'Rodri', section: 'Spain', type: '-' },
  { code: 'ESP11', title: 'Pedri', section: 'Spain', type: '-' },
  { code: 'ESP12', title: 'Fabian Ruiz', section: 'Spain', type: '-' },
  { code: 'ESP13', title: 'Team Photo', section: 'Spain', type: '-' },
  { code: 'ESP14', title: 'Mikel Merino', section: 'Spain', type: '-' },
  { code: 'ESP15', title: 'Lamine Yamal', section: 'Spain', type: '-' },
  { code: 'ESP16', title: 'Dani Olmo', section: 'Spain', type: '-' },
  { code: 'ESP17', title: 'Nico Williams', section: 'Spain', type: '-' },
  { code: 'ESP18', title: 'Ferran Torres', section: 'Spain', type: '-' },
  { code: 'ESP19', title: 'Álvaro Morata', section: 'Spain', type: '-' },
  { code: 'ESP20', title: 'Mikel Oyarzabal', section: 'Spain', type: '-' },
  { code: 'CPV1', title: 'Emblem', section: 'Cape Verde', type: 'foil' },
  { code: 'CPV2', title: 'Vozinha', section: 'Cape Verde', type: '-' },
  { code: 'CPV3', title: 'Logan Costa', section: 'Cape Verde', type: '-' },
  { code: 'CPV4', title: 'Pico', section: 'Cape Verde', type: '-' },
  { code: 'CPV5', title: 'Diney', section: 'Cape Verde', type: '-' },
  { code: 'CPV6', title: 'Steven Moreira', section: 'Cape Verde', type: '-' },
  { code: 'CPV7', title: 'Wagner Pina', section: 'Cape Verde', type: '-' },
  { code: 'CPV8', title: 'Joao Paulo', section: 'Cape Verde', type: '-' },
  { code: 'CPV9', title: 'Yannick Semedo', section: 'Cape Verde', type: '-' },
  { code: 'CPV10', title: 'Kevin Pina', section: 'Cape Verde', type: '-' },
  { code: 'CPV11', title: 'Patrick Andrade', section: 'Cape Verde', type: '-' },
  { code: 'CPV12', title: 'Jamiro Monteiro', section: 'Cape Verde', type: '-' },
  { code: 'CPV13', title: 'Team Photo', section: 'Cape Verde', type: '-' },
  { code: 'CPV14', title: 'Deroy Duarte', section: 'Cape Verde', type: '-' },
  { code: 'CPV15', title: 'Garry Rodrigues', section: 'Cape Verde', type: '-' },
  { code: 'CPV16', title: 'Jovane Cabral', section: 'Cape Verde', type: '-' },
  { code: 'CPV17', title: 'Ryan Mendes', section: 'Cape Verde', type: '-' },
  { code: 'CPV18', title: 'Dailon Livramento', section: 'Cape Verde', type: '-' },
  { code: 'CPV19', title: 'Willy Semedo', section: 'Cape Verde', type: '-' },
  { code: 'CPV20', title: 'Bebe', section: 'Cape Verde', type: '-' },
  { code: 'KSA1', title: 'Emblem', section: 'Saudi Arabia', type: 'foil' },
  { code: 'KSA2', title: 'Nawaf Alaqidi', section: 'Saudi Arabia', type: '-' },
  { code: 'KSA3', title: 'Abdulrahman Al-Sanbi', section: 'Saudi Arabia', type: '-' },
  { code: 'KSA4', title: 'Saud Abdulhamid', section: 'Saudi Arabia', type: '-' },
  { code: 'KSA5', title: 'Nawaf Bouwashl', section: 'Saudi Arabia', type: '-' },
  { code: 'KSA6', title: 'Jihad Thakri', section: 'Saudi Arabia', type: '-' },
  { code: 'KSA7', title: 'Moteb Al-Harbi', section: 'Saudi Arabia', type: '-' },
  { code: 'KSA8', title: 'Hassan Altambakti', section: 'Saudi Arabia', type: '-' },
  { code: 'KSA9', title: 'Musab Aljuwayr', section: 'Saudi Arabia', type: '-' },
  { code: 'KSA10', title: 'Ziyad Aljohani', section: 'Saudi Arabia', type: '-' },
  { code: 'KSA11', title: 'Abdullah Alkhaibari', section: 'Saudi Arabia', type: '-' },
  { code: 'KSA12', title: 'Nasser Aldawsari', section: 'Saudi Arabia', type: '-' },
  { code: 'KSA13', title: 'Team Photo', section: 'Saudi Arabia', type: '-' },
  { code: 'KSA14', title: 'Saleh Abu Alshamat', section: 'Saudi Arabia', type: '-' },
  { code: 'KSA15', title: 'Marwan Alsahafi', section: 'Saudi Arabia', type: '-' },
  { code: 'KSA16', title: 'Salem Aldawsari', section: 'Saudi Arabia', type: '-' },
  { code: 'KSA17', title: 'Abdulrahman Al-Aboud', section: 'Saudi Arabia', type: '-' },
  { code: 'KSA18', title: 'Feras Akbrikan', section: 'Saudi Arabia', type: '-' },
  { code: 'KSA19', title: 'Saleh Alshehri', section: 'Saudi Arabia', type: '-' },
  { code: 'KSA20', title: 'Abdullah Al-Hamdan', section: 'Saudi Arabia', type: '-' },
  { code: 'URU1', title: 'Emblem', section: 'Uruguay', type: 'foil' },
  { code: 'URU2', title: 'Sergio Rochet', section: 'Uruguay', type: '-' },
  { code: 'URU3', title: 'Santiago Mele', section: 'Uruguay', type: '-' },
  { code: 'URU4', title: 'Ronald Araujo', section: 'Uruguay', type: '-' },
  { code: 'URU5', title: 'José María Giménez', section: 'Uruguay', type: '-' },
  { code: 'URU6', title: 'Sebastian Caceres', section: 'Uruguay', type: '-' },
  { code: 'URU7', title: 'Mathias Olivera', section: 'Uruguay', type: '-' },
  { code: 'URU8', title: 'Guillermo Varela', section: 'Uruguay', type: '-' },
  { code: 'URU9', title: 'Nahitan Nandez', section: 'Uruguay', type: '-' },
  { code: 'URU10', title: 'Federico Valverde', section: 'Uruguay', type: '-' },
  { code: 'URU11', title: 'Giorgian De Arrascaeta', section: 'Uruguay', type: '-' },
  { code: 'URU12', title: 'Rodrigo Bentancur', section: 'Uruguay', type: '-' },
  { code: 'URU13', title: 'Team Photo', section: 'Uruguay', type: '-' },
  { code: 'URU14', title: 'Manuel Ugarte', section: 'Uruguay', type: '-' },
  { code: 'URU15', title: 'Nicolás de la Cruz', section: 'Uruguay', type: '-' },
  { code: 'URU16', title: 'Maxi Araujo', section: 'Uruguay', type: '-' },
  { code: 'URU17', title: 'Darwin Núñez', section: 'Uruguay', type: '-' },
  { code: 'URU18', title: 'Federico Viñas', section: 'Uruguay', type: '-' },
  { code: 'URU19', title: 'Rodrigo Aguirre', section: 'Uruguay', type: '-' },
  { code: 'URU20', title: 'Facundo Pellistri', section: 'Uruguay', type: '-' },
  { code: 'FRA1', title: 'Emblem', section: 'France', type: 'foil' },
  { code: 'FRA2', title: 'Mike Maignan', section: 'France', type: '-' },
  { code: 'FRA3', title: 'Theo Hernandez', section: 'France', type: '-' },
  { code: 'FRA4', title: 'William Saliba', section: 'France', type: '-' },
  { code: 'FRA5', title: 'Jules Kounde', section: 'France', type: '-' },
  { code: 'FRA6', title: 'Ibrahima Konate', section: 'France', type: '-' },
  { code: 'FRA7', title: 'Dayot Upamecano', section: 'France', type: '-' },
  { code: 'FRA8', title: 'Lucas Digne', section: 'France', type: '-' },
  { code: 'FRA9', title: 'Aurélien Tchouaméni', section: 'France', type: '-' },
  { code: 'FRA10', title: 'Eduardo Camavinga', section: 'France', type: '-' },
  { code: 'FRA11', title: 'Manu Kone', section: 'France', type: '-' },
  { code: 'FRA12', title: 'Adrien Rabiot', section: 'France', type: '-' },
  { code: 'FRA13', title: 'Team Photo', section: 'France', type: '-' },
  { code: 'FRA14', title: 'Michael Olise', section: 'France', type: '-' },
  { code: 'FRA15', title: 'Ousmane Dembele', section: 'France', type: '-' },
  { code: 'FRA16', title: 'Bradley Barcola', section: 'France', type: '-' },
  { code: 'FRA17', title: 'Désiré Doué', section: 'France', type: '-' },
  { code: 'FRA18', title: 'Kingsley Coman', section: 'France', type: '-' },
  { code: 'FRA19', title: 'Hugo Ekitike', section: 'France', type: '-' },
  { code: 'SEN1', title: 'Emblem', section: 'Senegal', type: 'foil' },
  { code: 'SEN2', title: 'Édouard Mendy', section: 'Senegal', type: '-' },
  { code: 'SEN3', title: 'Yehvann Diouf', section: 'Senegal', type: '-' },
  { code: 'SEN4', title: 'Moussa Niakhaté', section: 'Senegal', type: '-' },
  { code: 'SEN5', title: 'Abdoulaye Seck', section: 'Senegal', type: '-' },
  { code: 'SEN6', title: 'Ismail Jakobs', section: 'Senegal', type: '-' },
  { code: 'SEN7', title: 'El Hadji Malick Diouf', section: 'Senegal', type: '-' },
  { code: 'SEN8', title: 'Kalidou Koulibaly', section: 'Senegal', type: '-' },
  { code: 'SEN9', title: 'Idrissa Gana Gueye', section: 'Senegal', type: '-' },
  { code: 'SEN10', title: 'Pape Matar Sarr', section: 'Senegal', type: '-' },
  { code: 'SEN11', title: 'Pape Gueye', section: 'Senegal', type: '-' },
  { code: 'SEN12', title: 'Habib Diarra', section: 'Senegal', type: '-' },
  { code: 'SEN13', title: 'Team Photo', section: 'Senegal', type: '-' },
  { code: 'SEN14', title: 'Lamine Camara', section: 'Senegal', type: '-' },
  { code: 'SEN15', title: 'Sadio Mane', section: 'Senegal', type: '-' },
  { code: 'SEN16', title: 'Ismaïla Sarr', section: 'Senegal', type: '-' },
  { code: 'SEN17', title: 'Boulaye Dia', section: 'Senegal', type: '-' },
  { code: 'SEN18', title: 'Iliman Ndiaye', section: 'Senegal', type: '-' },
  { code: 'SEN19', title: 'Nicolas Jackson', section: 'Senegal', type: '-' },
  { code: 'SEN20', title: 'Krepin Diatta', section: 'Senegal', type: '-' },
  { code: 'IRQ1', title: 'Emblem', section: 'Iraq', type: 'foil' },
  { code: 'IRQ2', title: 'Jalal Hassan', section: 'Iraq', type: '-' },
  { code: 'IRQ3', title: 'Rebin Sulaka', section: 'Iraq', type: '-' },
  { code: 'IRQ4', title: 'Hussein Ali', section: 'Iraq', type: '-' },
  { code: 'IRQ5', title: 'Akam Hashem', section: 'Iraq', type: '-' },
  { code: 'IRQ6', title: 'Merchas Doski', section: 'Iraq', type: '-' },
  { code: 'IRQ7', title: 'Zaid Tahseen', section: 'Iraq', type: '-' },
  { code: 'IRQ8', title: 'Manaf Younis', section: 'Iraq', type: '-' },
  { code: 'IRQ9', title: 'Zidane Iqbal', section: 'Iraq', type: '-' },
  { code: 'IRQ10', title: 'Amir Al-Ammari', section: 'Iraq', type: '-' },
  { code: 'IRQ11', title: 'Ibrahim Bavesh', section: 'Iraq', type: '-' },
  { code: 'IRQ12', title: 'Ali Jasim', section: 'Iraq', type: '-' },
  { code: 'IRQ13', title: 'Team Photo', section: 'Iraq', type: '-' },
  { code: 'IRQ14', title: 'Youssef Amyn', section: 'Iraq', type: '-' },
  { code: 'IRQ15', title: 'Aimar Sher', section: 'Iraq', type: '-' },
  { code: 'IRQ16', title: 'Marko Farji', section: 'Iraq', type: '-' },
  { code: 'IRQ17', title: 'Osama Rashid', section: 'Iraq', type: '-' },
  { code: 'IRQ18', title: 'Ali Al-Hamadi', section: 'Iraq', type: '-' },
  { code: 'IRQ19', title: 'Aymen Hussein', section: 'Iraq', type: '-' },
  { code: 'IRQ20', title: 'Mohanad Ali', section: 'Iraq', type: '-' },
  { code: 'NOR1', title: 'Emblem', section: 'Norway', type: 'foil' },
  { code: 'NOR2', title: 'Orjan Nyland', section: 'Norway', type: '-' },
  { code: 'NOR3', title: 'Julian Ryerson', section: 'Norway', type: '-' },
  { code: 'NOR4', title: 'Leo Ostigård', section: 'Norway', type: '-' },
  { code: 'NOR5', title: 'Kristoffer Vassbakk Ajer', section: 'Norway', type: '-' },
  { code: 'NOR6', title: 'Marcus Holmgren Pedersen', section: 'Norway', type: '-' },
  { code: 'NOR7', title: 'David Møller Wolfe', section: 'Norway', type: '-' },
  { code: 'NOR8', title: 'Torbjørn Heggem', section: 'Norway', type: '-' },
  { code: 'NOR9', title: 'Morten Thorsby', section: 'Norway', type: '-' },
  { code: 'NOR10', title: 'Martin Ødegaard', section: 'Norway', type: '-' },
  { code: 'NOR11', title: 'Sander Berge', section: 'Norway', type: '-' },
  { code: 'NOR12', title: 'Andreas Schjelderup', section: 'Norway', type: '-' },
  { code: 'NOR13', title: 'Team Photo', section: 'Norway', type: '-' },
  { code: 'NOR14', title: 'Patrick Berg', section: 'Norway', type: '-' },
  { code: 'NOR15', title: 'Erling Haaland', section: 'Norway', type: '-' },
  { code: 'NOR16', title: 'Alexander Sørloth', section: 'Norway', type: '-' },
  { code: 'NOR17', title: 'Aron Dønnum', section: 'Norway', type: '-' },
  { code: 'NOR18', title: 'Jorgen Strand Larsen', section: 'Norway', type: '-' },
  { code: 'NOR19', title: 'Antonio Nusa', section: 'Norway', type: '-' },
  { code: 'NOR20', title: 'Oscar Bobb', section: 'Norway', type: '-' },
  { code: 'ARG1', title: 'Emblem', section: 'Argentina', type: 'foil' },
  { code: 'ARG2', title: 'Emiliano Martinez', section: 'Argentina', type: '-' },
  { code: 'ARG3', title: 'Nahuel Molina', section: 'Argentina', type: '-' },
  { code: 'ARG4', title: 'Cristian Romero', section: 'Argentina', type: '-' },
  { code: 'ARG5', title: 'Nicolas Otamendi', section: 'Argentina', type: '-' },
  { code: 'ARG6', title: 'Nicolas Tagliafico', section: 'Argentina', type: '-' },
  { code: 'ARG7', title: 'Leonardo Balerdi', section: 'Argentina', type: '-' },
  { code: 'ARG8', title: 'Enzo Fernandez', section: 'Argentina', type: '-' },
  { code: 'ARG9', title: 'Alexis Mac Allister', section: 'Argentina', type: '-' },
  { code: 'ARG10', title: 'Rodrigo De Paul', section: 'Argentina', type: '-' },
  { code: 'ARG11', title: 'Exequiel Palacios', section: 'Argentina', type: '-' },
  { code: 'ARG12', title: 'Leandro Paredes', section: 'Argentina', type: '-' },
  { code: 'ARG13', title: 'Team Photo', section: 'Argentina', type: '-' },
  { code: 'ARG14', title: 'Nico Paz', section: 'Argentina', type: '-' },
  { code: 'ARG15', title: 'Franco Mastantuono', section: 'Argentina', type: '-' },
  { code: 'ARG16', title: 'Nico Gonzalez', section: 'Argentina', type: '-' },
  { code: 'ARG17', title: 'Lionel Messi', section: 'Argentina', type: '-' },
  { code: 'ARG18', title: 'Lautaro Martinez', section: 'Argentina', type: '-' },
  { code: 'ARG19', title: 'Julian Alvarez', section: 'Argentina', type: '-' },
  { code: 'ARG20', title: 'Giuliano Simeone', section: 'Argentina', type: '-' },
  { code: 'ALG1', title: 'Emblem', section: 'Algeria', type: 'foil' },
  { code: 'ALG2', title: 'Alexis Guendouz', section: 'Algeria', type: '-' },
  { code: 'ALG3', title: 'Ramy Bensebaini', section: 'Algeria', type: '-' },
  { code: 'ALG4', title: 'Youcef Atal', section: 'Algeria', type: '-' },
  { code: 'ALG5', title: 'Rayan Aït-Nouri', section: 'Algeria', type: '-' },
  { code: 'ALG6', title: 'Mohamed Amine Tougai', section: 'Algeria', type: '-' },
  { code: 'ALG7', title: 'Aïssa Mandi', section: 'Algeria', type: '-' },
  { code: 'ALG8', title: 'Ismael Bennacer', section: 'Algeria', type: '-' },
  { code: 'ALG9', title: 'Houssem Aouar', section: 'Algeria', type: '-' },
  { code: 'ALG10', title: 'Hicham Boudaoui', section: 'Algeria', type: '-' },
  { code: 'ALG11', title: 'Ramiz Zerrouki', section: 'Algeria', type: '-' },
  { code: 'ALG12', title: 'Nabil Bentaleb', section: 'Algeria', type: '-' },
  { code: 'ALG13', title: 'Team Photo', section: 'Algeria', type: '-' },
  { code: 'ALG14', title: 'Farés Chaibi', section: 'Algeria', type: '-' },
  { code: 'ALG15', title: 'Riyad Mahrez', section: 'Algeria', type: '-' },
  { code: 'ALG16', title: 'Said Benrahma', section: 'Algeria', type: '-' },
  { code: 'ALG17', title: 'Anis Hadj Moussa', section: 'Algeria', type: '-' },
  { code: 'ALG18', title: 'Amine Gouiri', section: 'Algeria', type: '-' },
  { code: 'ALG19', title: 'Baghdad Bounedjah', section: 'Algeria', type: '-' },
  { code: 'ALG20', title: 'Mohammed Amoura', section: 'Algeria', type: '-' },
  { code: 'AUT1', title: 'Emblem', section: 'Austria', type: 'foil' },
  { code: 'AUT2', title: 'Alexander Schlager', section: 'Austria', type: '-' },
  { code: 'AUT3', title: 'Patrick Pentz', section: 'Austria', type: '-' },
  { code: 'AUT4', title: 'David Alaba', section: 'Austria', type: '-' },
  { code: 'AUT5', title: 'Kevin Danso', section: 'Austria', type: '-' },
  { code: 'AUT6', title: 'Philipp Lienhart', section: 'Austria', type: '-' },
  { code: 'AUT7', title: 'Stefan Posch', section: 'Austria', type: '-' },
  { code: 'AUT8', title: 'Phillipp Mwene', section: 'Austria', type: '-' },
  { code: 'AUT9', title: 'Alexander Prass', section: 'Austria', type: '-' },
  { code: 'AUT10', title: 'Xaver Schlager', section: 'Austria', type: '-' },
  { code: 'AUT11', title: 'Marcel Sabitzer', section: 'Austria', type: '-' },
  { code: 'AUT12', title: 'Konrad Laimer', section: 'Austria', type: '-' },
  { code: 'AUT13', title: 'Team Photo', section: 'Austria', type: '-' },
  { code: 'AUT14', title: 'Florian Grillitsch', section: 'Austria', type: '-' },
  { code: 'AUT15', title: 'Nicolas Seiwald', section: 'Austria', type: '-' },
  { code: 'AUT16', title: 'Romano Schmid', section: 'Austria', type: '-' },
  { code: 'AUT17', title: 'Patrick Wimmer', section: 'Austria', type: '-' },
  { code: 'AUT18', title: 'Christoph Baumgartner', section: 'Austria', type: '-' },
  { code: 'AUT19', title: 'Michael Gregoritsch', section: 'Austria', type: '-' },
  { code: 'AUT20', title: 'Marko Arnautović', section: 'Austria', type: '-' },
  { code: 'JOR1', title: 'Emblem', section: 'Jordan', type: 'foil' },
  { code: 'JOR2', title: 'Yazeed Abulaila', section: 'Jordan', type: '-' },
  { code: 'JOR3', title: 'Ihsan Haddad', section: 'Jordan', type: '-' },
  { code: 'JOR4', title: 'Mohammad Abu Hashish', section: 'Jordan', type: '-' },
  { code: 'JOR5', title: 'Yazan Al-Arab', section: 'Jordan', type: '-' },
  { code: 'JOR6', title: 'Abdallah Nasib', section: 'Jordan', type: '-' },
  { code: 'JOR7', title: 'Saleem Obaid', section: 'Jordan', type: '-' },
  { code: 'JOR8', title: 'Mohammad Abualnadi', section: 'Jordan', type: '-' },
  { code: 'JOR9', title: 'Ibrahim Saadeh', section: 'Jordan', type: '-' },
  { code: 'JOR10', title: 'Nizar Al-Rashdan', section: 'Jordan', type: '-' },
  { code: 'JOR11', title: 'Noor Al-Rawabdeh', section: 'Jordan', type: '-' },
  { code: 'JOR12', title: 'Mohannad Abu Taha', section: 'Jordan', type: '-' },
  { code: 'JOR13', title: 'Team Photo', section: 'Jordan', type: '-' },
  { code: 'JOR14', title: 'Amer Jamous', section: 'Jordan', type: '-' },
  { code: 'JOR15', title: 'Musa Al-Taamari', section: 'Jordan', type: '-' },
  { code: 'JOR16', title: 'Yazan Al-Naimat', section: 'Jordan', type: '-' },
  { code: 'JOR17', title: 'Mahmoud Al-Mardi', section: 'Jordan', type: '-' },
  { code: 'JOR18', title: 'Ali Olwan', section: 'Jordan', type: '-' },
  { code: 'JOR19', title: 'Mohammad Abu Zrayq', section: 'Jordan', type: '-' },
  { code: 'JOR20', title: 'Ibrahim Sabra', section: 'Jordan', type: '-' },
  { code: 'POR1', title: 'Emblem', section: 'Portugal', type: 'foil' },
  { code: 'POR2', title: 'Diogo Costa', section: 'Portugal', type: '-' },
  { code: 'POR3', title: 'José Sá', section: 'Portugal', type: '-' },
  { code: 'POR4', title: 'Ruben Dias', section: 'Portugal', type: '-' },
  { code: 'POR5', title: 'João Cancelo', section: 'Portugal', type: '-' },
  { code: 'POR6', title: 'Diogo Dalot', section: 'Portugal', type: '-' },
  { code: 'POR7', title: 'Nuno Mendes', section: 'Portugal', type: '-' },
  { code: 'POR8', title: 'Gonçalo Inácio', section: 'Portugal', type: '-' },
  { code: 'POR9', title: 'Bernardo Silva', section: 'Portugal', type: '-' },
  { code: 'POR10', title: 'Bruno Fernandes', section: 'Portugal', type: '-' },
  { code: 'POR11', title: 'Ruben Neves', section: 'Portugal', type: '-' },
  { code: 'POR12', title: 'Vitinha', section: 'Portugal', type: '-' },
  { code: 'POR13', title: 'Team Photo', section: 'Portugal', type: '-' },
  { code: 'POR14', title: 'João Neves', section: 'Portugal', type: '-' },
  { code: 'POR15', title: 'Cristiano Ronaldo', section: 'Portugal', type: '-' },
  { code: 'POR16', title: 'Francisco Trincao', section: 'Portugal', type: '-' },
  { code: 'POR17', title: 'João Felix', section: 'Portugal', type: '-' },
  { code: 'POR18', title: 'Gonçalo Ramos', section: 'Portugal', type: '-' },
  { code: 'POR19', title: 'Pedro Neto', section: 'Portugal', type: '-' },
  { code: 'POR20', title: 'Rafael Leão', section: 'Portugal', type: '-' },
  { code: 'COD1', title: 'Emblem', section: 'Congo DR', type: 'foil' },
  { code: 'COD2', title: 'Lionel Mpasi-Nzau', section: 'Congo DR', type: '-' },
  { code: 'COD3', title: 'Aaron Wan-Bissaka', section: 'Congo DR', type: '-' },
  { code: 'COD4', title: 'Axel Tuanzebe', section: 'Congo DR', type: '-' },
  { code: 'COD5', title: 'Arthur Masuaku', section: 'Congo DR', type: '-' },
  { code: 'COD6', title: 'Chancel Mbemba', section: 'Congo DR', type: '-' },
  { code: 'COD7', title: 'Joris Kayembe', section: 'Congo DR', type: '-' },
  { code: 'COD8', title: 'Charles Pickel', section: 'Congo DR', type: '-' },
  { code: 'COD9', title: 'Ngal\'ayel Mukau', section: 'Congo DR', type: '-' },
  { code: 'COD10', title: 'Edo Kayembe', section: 'Congo DR', type: '-' },
  { code: 'COD11', title: 'Samuel Moutoussamy', section: 'Congo DR', type: '-' },
  { code: 'COD12', title: 'Noah Sadiki', section: 'Congo DR', type: '-' },
  { code: 'COD13', title: 'Team Photo', section: 'Congo DR', type: '-' },
  { code: 'COD14', title: 'Théo Bongonda', section: 'Congo DR', type: '-' },
  { code: 'COD15', title: 'Meschak Elia', section: 'Congo DR', type: '-' },
  { code: 'COD16', title: 'Yoane Wissa', section: 'Congo DR', type: '-' },
  { code: 'COD17', title: 'Brian Cipenga', section: 'Congo DR', type: '-' },
  { code: 'COD18', title: 'Fiston Mayele', section: 'Congo DR', type: '-' },
  { code: 'COD19', title: 'Cédric Bakambu', section: 'Congo DR', type: '-' },
  { code: 'COD20', title: 'Nathanaël Mbuku', section: 'Congo DR', type: '-' },
  { code: 'UZB1', title: 'Emblem', section: 'Uzbekistan', type: 'foil' },
  { code: 'UZB2', title: 'Utkir Yusupov', section: 'Uzbekistan', type: '-' },
  { code: 'UZB3', title: 'Farrukh Savfiev', section: 'Uzbekistan', type: '-' },
  { code: 'UZB4', title: 'Sherzod Nasrullaev', section: 'Uzbekistan', type: '-' },
  { code: 'UZB5', title: 'Umar Eshmurodov', section: 'Uzbekistan', type: '-' },
  { code: 'UZB6', title: 'Husniddin Aliqulov', section: 'Uzbekistan', type: '-' },
  { code: 'UZB7', title: 'Rustamjon Ashurmatov', section: 'Uzbekistan', type: '-' },
  { code: 'UZB8', title: 'Khojiakbar Alijonov', section: 'Uzbekistan', type: '-' },
  { code: 'UZB9', title: 'Abdukodir Khusanov', section: 'Uzbekistan', type: '-' },
  { code: 'UZB10', title: 'Odiljon Hamrobekov', section: 'Uzbekistan', type: '-' },
  { code: 'UZB11', title: 'Otabek Shukurov', section: 'Uzbekistan', type: '-' },
  { code: 'UZB12', title: 'Jamshid Iskanderov', section: 'Uzbekistan', type: '-' },
  { code: 'UZB13', title: 'Team Photo', section: 'Uzbekistan', type: '-' },
  { code: 'UZB14', title: 'Azizbek Turgunboev', section: 'Uzbekistan', type: '-' },
  { code: 'UZB15', title: 'Khojimat Erkinov', section: 'Uzbekistan', type: '-' },
  { code: 'UZB16', title: 'Eldor Shomurodov', section: 'Uzbekistan', type: '-' },
  { code: 'UZB17', title: 'Oston Urunov', section: 'Uzbekistan', type: '-' },
  { code: 'UZB18', title: 'Jaloliddin Masharipov', section: 'Uzbekistan', type: '-' },
  { code: 'UZB19', title: 'Igor Sergeev', section: 'Uzbekistan', type: '-' },
  { code: 'UZB20', title: 'Abbosbek Fayzullaev', section: 'Uzbekistan', type: '-' },
  { code: 'COL1', title: 'Emblem', section: 'Colombia', type: 'foil' },
  { code: 'COL2', title: 'Camilo Vargas', section: 'Colombia', type: '-' },
  { code: 'COL3', title: 'David Ospina', section: 'Colombia', type: '-' },
  { code: 'COL4', title: 'Dávinson Sánchez', section: 'Colombia', type: '-' },
  { code: 'COL5', title: 'Yerry Mina', section: 'Colombia', type: '-' },
  { code: 'COL6', title: 'Daniel Munoz', section: 'Colombia', type: '-' },
  { code: 'COL7', title: 'Johan Mojica', section: 'Colombia', type: '-' },
  { code: 'COL8', title: 'Jhon Lucumí', section: 'Colombia', type: '-' },
  { code: 'COL9', title: 'Santiago Arias', section: 'Colombia', type: '-' },
  { code: 'COL10', title: 'Jefferson Lerma', section: 'Colombia', type: '-' },
  { code: 'COL11', title: 'Kevin Castaño', section: 'Colombia', type: '-' },
  { code: 'COL12', title: 'Richard Rios', section: 'Colombia', type: '-' },
  { code: 'COL13', title: 'Team Photo', section: 'Colombia', type: '-' },
  { code: 'COL14', title: 'James Rodriguez', section: 'Colombia', type: '-' },
  { code: 'COL15', title: 'Juan Fernando Quintero', section: 'Colombia', type: '-' },
  { code: 'COL16', title: 'Jorge Carrascal', section: 'Colombia', type: '-' },
  { code: 'COL17', title: 'Jhon Arias', section: 'Colombia', type: '-' },
  { code: 'COL18', title: 'Jhon Cordova', section: 'Colombia', type: '-' },
  { code: 'COL19', title: 'Luis Suarez', section: 'Colombia', type: '-' },
  { code: 'COL20', title: 'Luis Diaz', section: 'Colombia', type: '-' },
  { code: 'ENG1', title: 'Emblem', section: 'England', type: 'foil' },
  { code: 'ENG2', title: 'Jordan Pickford', section: 'England', type: '-' },
  { code: 'ENG3', title: 'John Stones', section: 'England', type: '-' },
  { code: 'ENG4', title: 'Marc Guéhi', section: 'England', type: '-' },
  { code: 'ENG5', title: 'Ezri Konsa', section: 'England', type: '-' },
  { code: 'ENG6', title: 'Trent Alexander-Arnold', section: 'England', type: '-' },
  { code: 'ENG7', title: 'Reece James', section: 'England', type: '-' },
  { code: 'ENG8', title: 'Dan Burn', section: 'England', type: '-' },
  { code: 'ENG9', title: 'Jordan Henderson', section: 'England', type: '-' },
  { code: 'ENG10', title: 'Declan Rice', section: 'England', type: '-' },
  { code: 'ENG11', title: 'Jude Bellingham', section: 'England', type: '-' },
  { code: 'ENG12', title: 'Cole Palmer', section: 'England', type: '-' },
  { code: 'ENG13', title: 'Team Photo', section: 'England', type: '-' },
  { code: 'ENG14', title: 'Morgan Rogers', section: 'England', type: '-' },
  { code: 'ENG15', title: 'Anthony Gordon', section: 'England', type: '-' },
  { code: 'ENG16', title: 'Phil Foden', section: 'England', type: '-' },
  { code: 'ENG17', title: 'Bukayo Saka', section: 'England', type: '-' },
  { code: 'ENG18', title: 'Harry Kane', section: 'England', type: '-' },
  { code: 'ENG19', title: 'Marcus Rashford', section: 'England', type: '-' },
  { code: 'ENG20', title: 'Ollie Watkins', section: 'England', type: '-' },
  { code: 'CRO1', title: 'Emblem', section: 'Croatia', type: 'foil' },
  { code: 'CRO2', title: 'Dominik Livaković', section: 'Croatia', type: '-' },
  { code: 'CRO3', title: 'Duje Caleta-Car', section: 'Croatia', type: '-' },
  { code: 'CRO4', title: 'Josko Gvardiol', section: 'Croatia', type: '-' },
  { code: 'CRO5', title: 'Josip Stanišić', section: 'Croatia', type: '-' },
  { code: 'CRO6', title: 'Luka Vušković', section: 'Croatia', type: '-' },
  { code: 'CRO7', title: 'Josip Sutalo', section: 'Croatia', type: '-' },
  { code: 'CRO8', title: 'Kristijan Jakic', section: 'Croatia', type: '-' },
  { code: 'CRO9', title: 'Luka Modrić', section: 'Croatia', type: '-' },
  { code: 'CRO10', title: 'Mateo Kovacic', section: 'Croatia', type: '-' },
  { code: 'CRO11', title: 'Martin Baturina', section: 'Croatia', type: '-' },
  { code: 'CRO12', title: 'Lovro Majer', section: 'Croatia', type: '-' },
  { code: 'CRO13', title: 'Team Photo', section: 'Croatia', type: '-' },
  { code: 'CRO14', title: 'Mario Pasalic', section: 'Croatia', type: '-' },
  { code: 'CRO15', title: 'Petar Sucic', section: 'Croatia', type: '-' },
  { code: 'CRO16', title: 'Ivan Perišić', section: 'Croatia', type: '-' },
  { code: 'CRO17', title: 'Marco Pasalic', section: 'Croatia', type: '-' },
  { code: 'CRO18', title: 'Ante Budimir', section: 'Croatia', type: '-' },
  { code: 'CRO19', title: 'Andrej Kramarić', section: 'Croatia', type: '-' },
  { code: 'CRO20', title: 'Franjo Ivanovic', section: 'Croatia', type: '-' },
  { code: 'GHA1', title: 'Emblem', section: 'Ghana', type: 'foil' },
  { code: 'GHA2', title: 'Lawrence Ati Zigi', section: 'Ghana', type: '-' },
  { code: 'GHA3', title: 'Tariq Lamptey', section: 'Ghana', type: '-' },
  { code: 'GHA4', title: 'Mohammed Salisu', section: 'Ghana', type: '-' },
  { code: 'GHA5', title: 'Alidu Seidu', section: 'Ghana', type: '-' },
  { code: 'GHA6', title: 'Alexander Djiku', section: 'Ghana', type: '-' },
  { code: 'GHA7', title: 'Gideon Mensah', section: 'Ghana', type: '-' },
  { code: 'GHA8', title: 'Caleb Yirenkyi', section: 'Ghana', type: '-' },
  { code: 'GHA9', title: 'Abdul Issahaku Fatawu', section: 'Ghana', type: '-' },
  { code: 'GHA10', title: 'Thomas Partey', section: 'Ghana', type: '-' },
  { code: 'GHA11', title: 'Salis Abdul Samed', section: 'Ghana', type: '-' },
  { code: 'GHA12', title: 'Kamaldeen Sulemana', section: 'Ghana', type: '-' },
  { code: 'GHA13', title: 'Team Photo', section: 'Ghana', type: '-' },
  { code: 'GHA14', title: 'Mohammed Kudus', section: 'Ghana', type: '-' },
  { code: 'GHA15', title: 'Inaki Williams', section: 'Ghana', type: '-' },
  { code: 'GHA16', title: 'Jordan Ayew', section: 'Ghana', type: '-' },
  { code: 'GHA17', title: 'André Ayew', section: 'Ghana', type: '-' },
  { code: 'GHA18', title: 'Joseph Paintsil', section: 'Ghana', type: '-' },
  { code: 'GHA19', title: 'Osman Bukari', section: 'Ghana', type: '-' },
  { code: 'GHA20', title: 'Antoine Semenyo', section: 'Ghana', type: '-' },
  { code: 'PAN1', title: 'Emblem', section: 'Panama', type: 'foil' },
  { code: 'PAN2', title: 'Orlando Mosquera', section: 'Panama', type: '-' },
  { code: 'PAN3', title: 'Luis Mejia', section: 'Panama', type: '-' },
  { code: 'PAN4', title: 'Fidel Escobar', section: 'Panama', type: '-' },
  { code: 'PAN5', title: 'Andres Andrade', section: 'Panama', type: '-' },
  { code: 'PAN6', title: 'Michael Amir Murillo', section: 'Panama', type: '-' },
  { code: 'PAN7', title: 'Eric Davis', section: 'Panama', type: '-' },
  { code: 'PAN8', title: 'Jose Cordoba', section: 'Panama', type: '-' },
  { code: 'PAN9', title: 'Cesar Blackman', section: 'Panama', type: '-' },
  { code: 'PAN10', title: 'Cristian Martinez', section: 'Panama', type: '-' },
  { code: 'PAN11', title: 'Aníbal Godoy', section: 'Panama', type: '-' },
  { code: 'PAN12', title: 'Adalberto Carrasquilla', section: 'Panama', type: '-' },
  { code: 'PAN13', title: 'Team Photo', section: 'Panama', type: '-' },
  { code: 'PAN14', title: 'Édgar Bárcenas', section: 'Panama', type: '-' },
  { code: 'PAN15', title: 'Carlos Harvey', section: 'Panama', type: '-' },
  { code: 'PAN16', title: 'Ismael Díaz', section: 'Panama', type: '-' },
  { code: 'PAN17', title: 'Jose Fajardo', section: 'Panama', type: '-' },
  { code: 'PAN18', title: 'Cecilio Waterman', section: 'Panama', type: '-' },
  { code: 'PAN19', title: 'Jose Luiz Rodriguez', section: 'Panama', type: '-' },
  { code: 'PAN20', title: 'Alberto Quintero', section: 'Panama', type: '-' },
  { code: 'LM', title: 'Lionel Messi', section: 'Argentina', type: 'Extra / Base' },
  { code: 'JD', title: 'Jérémy Doku', section: 'Belgium', type: 'Extra / Base' },
  { code: 'VJ', title: 'Vinícíús Júnior', section: 'Brazil', type: 'Extra / Base' },
  { code: 'AD', title: 'Alphonso Davies', section: 'Canada', type: 'Extra / Base' },
  { code: 'LD', title: 'Luis Díaz', section: 'Colombia', type: 'Extra / Base' },
  { code: 'LMO', title: 'Luka Modrić', section: 'Croatia', type: 'Extra / Base' },
  { code: 'MC', title: 'Moisés Caicedo', section: 'Ecuador', type: 'Extra / Base' },
  { code: 'MS', title: 'Mohamed Salah', section: 'Egypt', type: 'Extra / Base' },
  { code: 'JB', title: 'Jude Bellingham', section: 'England', type: 'Extra / Base' },
  { code: 'KM', title: 'Kylian Mbappé', section: 'France', type: 'Extra / Base' },
  { code: 'FW', title: 'Florian Wirtz', section: 'Germany', type: 'Extra / Base' },
  { code: 'RJ', title: 'Raúl Jiménez', section: 'Mexico', type: 'Extra / Base' },
  { code: 'AH', title: 'Achraf Hakimi', section: 'Morocco', type: 'Extra / Base' },
  { code: 'EH', title: 'Erling Haaland', section: 'Norway', type: 'Extra / Base' },
  { code: 'CG', title: 'Cody Gakpo', section: 'Netherlands', type: 'Extra / Base' },
  { code: 'CR', title: 'Cristiano Ronaldo', section: 'Portugal', type: 'Extra / Base' },
  { code: 'HS', title: 'Heung-min Son', section: 'South Korea', type: 'Extra / Base' },
  { code: 'LY', title: 'Lamine Yamal', section: 'Spain', type: 'Extra / Base' },
  { code: 'CP', title: 'Christian Pulisic', section: 'USA', type: 'Extra / Base' },
  { code: 'FV', title: 'Federico Valverde', section: 'Uruguay', type: 'Extra / Base' },
]

async function main() {
  console.log('Seeding database...')

  await prisma.sticker.deleteMany()

  const result = await prisma.sticker.createMany({
    data: stickers.map(s => ({
      code: s.code,
      title: s.title,
      section: s.section,
      type: s.type,
      collected: false,
    })),
  })

  console.log(`Created ${result.count} stickers`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
